import { Template } from '@/types';

export const TEMPLATES: Template[] = [
  {
    id: 'cinematic-sweep',
    name: 'Cinematic Sweep',
    description: 'Slow Ken Burns zoom with elegant fade transitions. Film-grade feel.',
    thumbnail: '/templates/cinematic.svg',
    style: 'cinematic',
    transitionType: 'crossfade',
    durationPerPhoto: 4,
    color: '#FFD700',
  },
  {
    id: 'dynamic-burst',
    name: 'Dynamic Burst',
    description: 'Fast cuts with scale-in animations and beat-synced transitions.',
    thumbnail: '/templates/dynamic.svg',
    style: 'dynamic',
    transitionType: 'slide',
    durationPerPhoto: 2.5,
    color: '#FF6B00',
  },
  {
    id: 'minimal-fade',
    name: 'Minimal Fade',
    description: 'Clean, simple crossfades with subtle pan. Let the photos speak.',
    thumbnail: '/templates/minimal.svg',
    style: 'minimal',
    transitionType: 'fade',
    durationPerPhoto: 3.5,
    color: '#FFFFFF',
  },
  {
    id: 'retro-vhs',
    name: 'Retro VHS',
    description: 'Vintage CRT scanlines, color bleed, and tape distortion effects.',
    thumbnail: '/templates/retro.svg',
    style: 'retro',
    transitionType: 'glitch',
    durationPerPhoto: 3,
    color: '#FF00FF',
  },
  {
    id: 'glitch-tech',
    name: 'Glitch Tech',
    description: 'Cyberpunk glitch transitions with RGB split and data corruption.',
    thumbnail: '/templates/glitch.svg',
    style: 'glitch',
    transitionType: 'glitch',
    durationPerPhoto: 2,
    color: '#00FFFF',
  },
  {
    id: 'parallax-depth',
    name: 'Parallax Depth',
    description: '3D parallax layers with depth-of-field. Faces auto-centered.',
    thumbnail: '/templates/parallax.svg',
    style: 'parallax',
    transitionType: 'parallax',
    durationPerPhoto: 4.5,
    color: '#7C3AED',
  },
];
